# Visualizzare df

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
games = pd.read_csv('/content/drive/MyDrive/TaskNBA/df_original/games.csv')
games_details = pd.read_csv('/content/drive/MyDrive/TaskNBA/df_original/games_details.csv', low_memory = False)
players = pd.read_csv('/content/drive/MyDrive/TaskNBA/df_original/players.csv')
ranking = pd.read_csv('/content/drive/MyDrive/TaskNBA/df_original/ranking.csv')
teams = pd.read_csv('/content/drive/MyDrive/TaskNBA/df_original/teams.csv')
# GGDPmerge = pd.read_csv('/content/drive/MyDrive/TaskNBA/GGDPmerge.csv', low_memory = False)

In [ ]:
games

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,...,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,...,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,...,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,...,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,...,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26646,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,...,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
26647,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,...,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
26648,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,...,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
26649,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,...,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
26650,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [ ]:
games_details

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668623,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,NaN,NaN,NaN,19,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,NaN
668624,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,NaN,NaN,NaN,23,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,NaN
668625,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,NaN,NaN,NaN,15,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,NaN
668626,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,NaN,NaN,NaN,19,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,NaN
668627,11200005,1610612743,DEN,Denver,201951,Ty Lawson,NaN,NaN,NaN,27,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,NaN

In [ ]:
players

           PLAYER_NAME     TEAM_ID  PLAYER_ID  SEASON
0        Royce O'Neale  1610612762    1626220    2019
1     Bojan Bogdanovic  1610612762     202711    2019
2          Rudy Gobert  1610612762     203497    2019
3     Donovan Mitchell  1610612762    1628378    2019
4          Mike Conley  1610612762     201144    2019
...                ...         ...        ...     ...
7223       Lanny Smith  1610612758     201831    2009
7224     Warren Carter  1610612752     201999    2009
7225      Bennet Davis  1610612751     201834    2009
7226    Brian Hamilton  1610612751     201646    2009
7227   Wesley Matthews  1610612762     500032    2009

[7228 rows x 4 columns]

In [ ]:
ranking

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,0,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,NaN
210338,1610612738,0,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,NaN
210339,1610612753,0,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,NaN
210340,1610612755,0,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,NaN
210341,1610612749,0,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,NaN

In [ ]:
teams

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends
5,0,1610612743,1976,2019,DEN,Nuggets,1976,Denver,Pepsi Center,19099.0,Stan Kroenke,Tim Connelly,Michael Malone,No Affiliate
6,0,1610612745,1967,2019,HOU,Rockets,1967,Houston,Toyota Center,18104.0,Tilman Fertitta,Daryl Morey,Mike D'Antoni,Rio Grande Valley Vipers
7,0,1610612746,1970,2019,LAC,Clippers,1970,Los Angeles,Staples Center,19060.0,Steve Ballmer,Michael Winger,Doc Rivers,Agua Caliente Clippers of Ontario
8,0,1610612747,1948,2019,LAL,Lakers,1948,Los Angeles,Staples Center,19060.0,Jerry Buss Family Trust,Rob Pelinka,Frank Vogel,South Bay Lakers
9,0,1610612748,1988,2019,MIA,Heat,1988,Miami,AmericanAirlines Arena,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce
10,0,1610612749,1968,2019,MIL,Bucks,1968,Milwaukee,Fiserv Forum,17500.0,Wesley Edens & Marc Lasry,Jon Horst,Mike Budenholzer,Wisconsin Herd
11,0,1610612750,1989,2019,MIN,Timberwolves,1989,Minnesota,Target Center,19356.0,Glen Taylor,Scott Layden,Ryan Saunders,Iowa Wolves
12,0,1610612751,1976,2019,BKN,Nets,1976,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Kenny Atkinson,Long Island Nets
13,0,1610612752,1946,2019,NYK,Knicks,1946,New York,Madison Square Garden,19763.0,Cablevision (James Dolan),Steve Mills,David Fizdale,Westchester Knicks
14,0,1610612753,1989,2019,ORL,Magic,1989,Orlando,Amway Center,0.0,Rick DeVos,John Hammond,Steve Clifford,Lakeland Magic
15,0,1610612754,1976,2019,IND,Pacers,1976,Indiana,Bankers Life Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Nate McMillan,Fort Wayne Mad Ants
16,0,1610612755,1949,2019,PHI,76ers,1949,Philadelphia,Wells Fargo Center,NaN,Joshua Harris,Elton Brand,Brett Brown,Delaware Blue Coats
17,0,1610612756,1968,2019,PHX,Suns,1968,Phoenix,Talking Stick Resort Arena,NaN,Robert Sarver,James Jones,Monty Williams,Northern Arizona Suns
18,0,1610612757,1970,2019,POR,Trail Blazers,1970,Portland,Moda Center,19980.0,Paul Allen,Neil Olshey,Terry Stotts,No Affiliate
19,0,1610612758,1948,2019,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
20,0,1610612759,1976,2019,SAS,Spurs,1976,San Antonio,AT&T Center,18694.0,Peter Holt,Brian Wright,Gregg Popovich,Austin Spurs
21,0,1610612760,1967,2019,OKC,Thunder,1967,Oklahoma City,Chesapeake Energy Arena,19163.0,Clay Bennett,Sam Presti,Billy Donovan,Oklahoma City Blue
22,0,1610612761,1995,2019,TOR,Raptors,1995,Toronto,Scotiabank Arena,19800.0,Maple Leaf Sports and Entertainment,Masai Ujiri,Nick Nurse,Raptors 905
23,0,1610612762,1974,2019,UTA,Jazz,1974,Utah,Vivint Smart Home Arena,20148.0,Greg Miller,Dennis Lindsey,Quin Snyder,Salt Lake City Stars
24,0,1610612763,1995,2019,MEM,Grizzlies,1995,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Taylor Jenkins,Memphis Hustle
25,0,1610612764,1961,2019,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
26,0,1610612765,1948,2019,DET,Pistons,1948,Detroit,Little Caesars Arena,21000.0,Tom Gores,Ed Stefanski,Dwane Casey,Grand Rapids Drive
27,0,1610612766,1988,2019,CHA,Hornets,1988,Charlotte,Spectrum Center,19026.0,Michael Jordan,Mitch Kupchak,James Borrego,Greensboro Swarm
28,0,1610612739,1970,2019,CLE,Cavaliers,1970,Cleveland,Quicken Loans Arena,20562.0,Dan Gilbert,Koby Altman,John Beilein,Canton Charge
29,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,Joe Lacob,Bob Myers,Steve Kerr,Santa Cruz Warriors

# Check NaN

In [ ]:
games = pd.read_csv('/content/games.csv')
games_details = pd.read_csv('/content/games_details.csv', low_memory = False)
# players = pd.read_csv('/content/drive/MyDrive/TaskNBA/players.csv')
# ranking = pd.read_csv('/content/drive/MyDrive/TaskNBA/ranking.csv')
teams = pd.read_csv('/content/teams.csv')

In [ ]:
games.isna().any()

GAME_DATE_EST       False
GAME_ID             False
GAME_STATUS_TEXT    False
HOME_TEAM_ID        False
VISITOR_TEAM_ID     False
SEASON              False
TEAM_ID_home        False
PTS_home            False
FG_PCT_home         False
FT_PCT_home         False
FG3_PCT_home        False
AST_home            False
REB_home            False
TEAM_ID_away        False
PTS_away            False
FG_PCT_away         False
FT_PCT_away         False
FG3_PCT_away        False
AST_away            False
REB_away            False
HOME_TEAM_WINS      False
dtype: bool

In [ ]:
games['PTS_away'].isna().sum()

0

In [ ]:
games[games['PTS_away'].isna()]

In [ ]:
games_details.isna().any()

GAME_ID              False
TEAM_ID              False
TEAM_ABBREVIATION    False
TEAM_CITY            False
PLAYER_ID            False
PLAYER_NAME          False
NICKNAME              True
START_POSITION        True
COMMENT               True
MIN                  False
FGM                  False
FGA                  False
FG_PCT               False
FG3M                 False
FG3A                 False
FG3_PCT              False
FTM                  False
FTA                  False
FT_PCT               False
OREB                 False
DREB                 False
REB                  False
AST                  False
STL                  False
BLK                  False
TO                   False
PF                   False
PTS                  False
PLUS_MINUS            True
dtype: bool

In [ ]:
games_details['MIN'].isna().sum()

0

In [ ]:
games_details[games_details['MIN'].isna()]

In [ ]:
(games_details['MIN'] == '0:00').any()

True

In [ ]:
(games_details['MIN'] == '0:00').sum()

0

In [ ]:
games_details[games_details['MIN'] == '0:00']

In [ ]:
players.isna().any()

PLAYER_NAME    False
TEAM_ID        False
PLAYER_ID      False
SEASON         False
dtype: bool

In [ ]:
ranking.isna().any()

TEAM_ID          False
LEAGUE_ID        False
SEASON_ID        False
STANDINGSDATE    False
CONFERENCE       False
TEAM             False
G                False
W                False
L                False
W_PCT            False
HOME_RECORD      False
ROAD_RECORD      False
RETURNTOPLAY      True
dtype: bool

In [ ]:
ranking['RETURNTOPLAY'].isna().sum()

206352

In [ ]:
ranking[ranking['RETURNTOPLAY'].isna()]

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,0,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,NaN
210338,1610612738,0,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,NaN
210339,1610612753,0,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,NaN
210340,1610612755,0,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,NaN
210341,1610612749,0,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,NaN

In [ ]:
teams.isna().any() # valori NaN per ARENACAPACITY

LEAGUE_ID             False
TEAM_ID               False
MIN_YEAR              False
MAX_YEAR              False
ABBREVIATION          False
NICKNAME              False
YEARFOUNDED           False
CITY                  False
ARENA                 False
ARENACAPACITY         False
OWNER                 False
GENERALMANAGER        False
HEADCOACH             False
DLEAGUEAFFILIATION    False
dtype: bool

In [ ]:
teams['ARENACAPACITY'].isna().sum()

4

In [ ]:
teams[teams['ARENACAPACITY'].isna()]

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
12,0,1610612751,1976,2019,BKN,Nets,1976,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Kenny Atkinson,Long Island Nets
16,0,1610612755,1949,2019,PHI,76ers,1949,Philadelphia,Wells Fargo Center,NaN,Joshua Harris,Elton Brand,Brett Brown,Delaware Blue Coats
17,0,1610612756,1968,2019,PHX,Suns,1968,Phoenix,Talking Stick Resort Arena,NaN,Robert Sarver,James Jones,Monty Williams,Northern Arizona Suns

# Modifiche

In [ ]:
gamesNA = games[games['PTS_away'].isna()]

In [ ]:
games = games.drop(index=gamesNA.index)

In [ ]:
games.to_csv('games.csv', index=False)

In [ ]:
games_detailsNA = games_details[games_details['MIN'].isna()]

In [ ]:
games_details = games_details.drop(index=games_detailsNA.index)

In [ ]:
games_details00 = games_details[games_details['MIN'] == '0:00']

In [ ]:
games_details = games_details.drop(index=games_details00.index)

In [ ]:
games_details.to_csv('games_details.csv', index=False)

In [ ]:
# Effettua la join sulla colonna 'GAME_ID'
merged_df = pd.merge(games_details, games[['GAME_ID', 'SEASON']], on='GAME_ID', how='left')

merged_df

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,SEASON
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0,2022
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0,2022
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0,2022
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0,2022
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559578,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,NaN,NaN,NaN,19,...,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,NaN,2012
559579,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,NaN,NaN,NaN,23,...,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,NaN,2012
559580,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,NaN,NaN,NaN,15,...,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,NaN,2012
559581,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,NaN,NaN,NaN,19,...,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,NaN,2012
559582,11200005,1610612743,DEN,Denver,201951,Ty Lawson,NaN,NaN,NaN,27,...,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,NaN,2012

In [ ]:
# Dividere la colonna 'MIN' in due colonne 'MINUTES' e 'SECONDS'
merged_df[['MINUTES', 'SECONDS']] = merged_df['MIN'].str.split(':', expand=True)

In [ ]:
# Conversione delle colonne in tipo numerico, se necessario
merged_df['MINUTES'] = pd.to_numeric(merged_df['MINUTES'])
merged_df['SECONDS'] = pd.to_numeric(merged_df['SECONDS']).fillna(0)

In [ ]:
# Calcolare la durata totale delle partite in minuti
merged_df['TOTAL_MINUTES'] = merged_df['MINUTES'] + merged_df['SECONDS'] / 60

In [ ]:
merged_df

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,STL,BLK,TO,PF,PTS,PLUS_MINUS,SEASON,MINUTES,SECONDS,TOTAL_MINUTES
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,0.0,2.0,5.0,2.0,-2.0,2022,18.0,6.0,18.100000
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,1.0,0.0,2.0,1.0,23.0,-14.0,2022,31.0,1.0,31.016667
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,0.0,2.0,4.0,13.0,-4.0,2022,21.0,42.0,21.700000
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,3.0,0.0,2.0,1.0,10.0,-18.0,2022,30.0,20.0,30.333333
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,0.0,2.0,2.0,19.0,0.0,2022,27.0,44.0,27.733333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559578,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,NaN,NaN,NaN,19,...,2.0,0.0,1.0,3.0,17.0,NaN,2012,19.0,0.0,19.000000
559579,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,NaN,NaN,NaN,23,...,1.0,0.0,3.0,3.0,18.0,NaN,2012,23.0,0.0,23.000000
559580,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,NaN,NaN,NaN,15,...,1.0,0.0,0.0,3.0,6.0,NaN,2012,15.0,0.0,15.000000
559581,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,NaN,NaN,NaN,19,...,0.0,0.0,4.0,2.0,2.0,NaN,2012,19.0,0.0,19.000000
559582,11200005,1610612743,DEN,Denver,201951,Ty Lawson,NaN,NaN,NaN,27,...,2.0,0.0,6.0,1.0,8.0,NaN,2012,27.0,0.0,27.000000

In [ ]:
merged_df.to_csv('games_details_seas.csv', index=False)

In [ ]:
# Modifiche a teams.csv

# Mappa dei valori da assegnare in base alla colonna 'CITY'
capacity_mapping = {
    'Brooklyn': 17732,
    'Orlando': 20000,
    'Philadelphia': 21000,
    'Phoenix': 18422,
    'New Orleans': 17791
}

# Sostituisci i valori NaN in base alla mappa
teams['ARENACAPACITY'] = teams.apply(lambda row: capacity_mapping[row['CITY']] if pd.isna(row['ARENACAPACITY']) else row['ARENACAPACITY'], axis=1)

In [ ]:
teams.to_csv('teams.csv', index=False)

# Lettura dataset puliti

In [ ]:
games = pd.read_csv('/content/drive/MyDrive/TaskNBA/games.csv')
games_details_orig = pd.read_csv('/content/drive/MyDrive/TaskNBA/games_details.csv', low_memory = False)
games_details = pd.read_csv('/content/drive/MyDrive/TaskNBA/games_details_seas.csv', low_memory = False)
players = pd.read_csv('/content/drive/MyDrive/TaskNBA/players.csv')
ranking = pd.read_csv('/content/drive/MyDrive/TaskNBA/ranking.csv')
teams = pd.read_csv('/content/drive/MyDrive/TaskNBA/teams.csv')